// ignore_for_file: constant_identifier_names

enum PageType {
  TOP,
  EDIT_CUSTOMER_INFO,
  INPUT_RECORD1,
  INPUT_RECORD2,
  INPUT_RECORD3,
  INPUT_RECORD4,
  INPUT_RECORD5,
  RECORD_LIST,
  RECORD_DETAIL,
  PRIVACY_POLICY,
}
