name: Run Sale Notification frontend unit test
on:
  push:
    # paths:
    #   - "webapps/sale_notification/frontend/**"
    branches: [main]
  # pull_request:
  #   paths:
  #     - "webapps/sale_notification/frontend/**"
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: ./web-apps/sale_notification/frontend
        run: npm install

      - name: Run tests
        working-directory: ./web-apps/sale_notification/frontend
        run: npm run test
